export const Barisal = [
    { value: "barguna", label: "Barguna" },
    { value: "agailjhara", label: "Agailjhara" },
    { value: "babuganj", label: "Babuganj" },
    { value: "barajalia", label: "Barajalia" },
    { value: "gouranadi", label: "Gouranadi" },
    { value: "mehendiganj", label: "Mehendiganj" },
    { value: "muladi", label: "Muladi" },
    { value: "sahebganj", label: "Sahebganj" },
    { value: "town", label: "Town" },
    { value: "uzirpur", label: "Uzirpur" },
    { value: "bhola", label: "Bhola" },
    { value: "jhalokati", label: "Jhalokati" },
    { value: "patuakhali", label: "Patuakhali" },
    { value: "pirojpur", label: "Pirojpur" },
];


export const Chittagong = [
    { value: "anawara", label: "Anawara" },
    { value: "bandarban", label: "Bandarban" },
    { value: "banshkhali", label: "Banshkhali" },
    { value: "barkal", label: "Barkal" },
    { value: "basurhat", label: "Basurhat" },
    { value: "begumganj", label: "Begumganj" },
    { value: "bilaichhari", label: "Bilaichhari" },
    { value: "boalkhali", label: "Boalkhali" },
    { value: "brahmanbaria", label: "Brahmanbaria" },
    { value: "brahmanbaria kasba", label: "Brahmanbaria Kasba" },
    { value: "brahmanbaria sarail", label: "Brahmanbaria Sarail" },
    { value: "chakaria", label: "Chakaria" },
    { value: "chandpur sadar", label: "Chandpur Sadar" },
    { value: "chatkhil", label: "Chatkhil" },
    { value: "chattogram sadar", label: "Chattogram Sadar" },
    { value: "chhagalnaia", label: "Chhagalnaia" },
    { value: "chouddagram", label: "Chouddagram" },
    { value: "comilla barura", label: "Comilla Barura" },
    { value: "comilla brahmanpara", label: "Comilla Brahmanpara" },
    { value: "comilla burichang", label: "Comilla Burichang" },
    { value: "comilla chandina", label: "Comilla Chandina" },
    { value: "comilla daudkandi", label: "Comilla Daudkandi" },
    { value: "comilla davidhar", label: "Comilla Davidhar" },
    { value: "comilla homna", label: "Comilla Homna" },
    { value: "comilla laksam", label: "Comilla Laksam" },
    { value: "comilla lalmai", label: "Comilla Lalmai" },
    { value: "comilla langalkot", label: "Comilla Langalkot" },
    { value: "comilla meghna", label: "Comilla Meghna" },
    { value: "comilla monohorganj", label: "Comilla Monohorganj" },
    { value: "comilla muradnagar", label: "Comilla Muradnagar" },
    { value: "comilla sadar", label: "Comilla Sadar" },
    { value: "cox's bazar sadar", label: "Cox's Bazar Sadar" },
    { value: "cox's bazar eidgaon upazila", label: "CoxsBazar Eidgaon Upazila" },
    { value: "daganbhuiyan", label: "Daganbhuiyan" },
    { value: "diginala", label: "Diginala" },
    { value: "eastjoara", label: "EastJoara" },
    { value: "faridganj", label: "Faridganj" },
    { value: "fatikchhari", label: "Fatikchhari" },
    { value: "feni", label: "Feni" },
    { value: "hajiganj", label: "Hajiganj" },
    { value: "hathazari", label: "Hathazari" },
    { value: "hatiya", label: "Hatiya" },
    { value: "hayemchar", label: "Hayemchar" },
    { value: "juraichhari", label: "Juraichhari" },
    { value: "kachua", label: "Kachua" },
    { value: "kaptai", label: "Kaptai" },
    { value: "kawkhali", label: "Kawkhali" },
    { value: "khagrachari", label: "Khagrachari" },
    { value: "kutubdia", label: "Kutubdia" },
    { value: "lakshmipur", label: "Lakshmipur" },
    { value: "langadu", label: "Langadu" },
    { value: "laxmichhari", label: "Laxmichhari" },
    { value: "lohagara", label: "Lohagara" },
    { value: "manikchhari", label: "Manikchhari" },
    { value: "matiranga", label: "Matiranga" },
    { value: "matlab", label: "Matlab" },
    { value: "mirsharai", label: "Mirsharai" },
    { value: "moheskhali", label: "Moheskhali" },
    { value: "nabinagar", label: "Nabinagar" },
    { value: "naniachhar", label: "Naniachhar" },
    { value: "noakhali", label: "Noakhali" },
    { value: "panchhari", label: "Panchhari" },
    { value: "pashurampur", label: "Pashurampur" },
    { value: "patiya", label: "Patiya" },
    { value: "rajsthali", label: "Rajsthali" },
    { value: "ramganj", label: "Ramganj" },
    { value: "ramgati", label: "Ramgati" },
    { value: "ramghar", label: "Ramghar" },
    { value: "ramu", label: "Ramu" },
    { value: "rangamati marishya", label: "Rangamati Marishya" },
    { value: "rangamati town", label: "Rangamati Town" },
    { value: "rangunia", label: "Rangunia" },
    { value: "raozan", label: "Raozan" },
    { value: "raypur", label: "Raypur" },
    { value: "sandwip", label: "Sandwip" },
    { value: "satkania", label: "Satkania" },
    { value: "senbag", label: "Senbag" },
    { value: "shahrasti", label: "Shahrasti" },
    { value: "sitakunda", label: "SitaKunda" },
    { value: "sonagazi", label: "Sonagazi" },
    { value: "teknaf", label: "Teknaf" },
    { value: "ukhia", label: "Ukhia" },
];

export const Dhaka = [
    { value: "dhaka north", label: "Dhaka North" },
    { value: "dhaka south", label: "Dhaka South" },
    { value: "faridpur", label: "Faridpur" },
    { value: "gazipur", label: "Gazipur" },
    { value: "gopalganj", label: "Gopalganj" },
    { value: "keraniganj", label: "Keraniganj" },
    { value: "kishoreganj", label: "Kishoreganj" },
    { value: "madaripur", label: "Madaripur" },
    { value: "manikganj shibloya", label: "Manikganj Shibloya" },
    { value: "manikganj singair", label: "Manikganj Singair" },
    { value: "manikganj town", label: "Manikganj Town" },
    { value: "munshiganj gajaria", label: "Munshiganj Gajaria" },
    { value: "munshiganj lohajong", label: "Munshiganj Lohajong" },
    { value: "munshiganj sirajdikhan", label: "Munshiganj Sirajdikhan" },
    { value: "munshiganj town", label: "Munshiganj Town" },
    { value: "narayanganj", label: "Narayanganj" },
    { value: "narsingdi", label: "Narsingdi" },
    { value: "nawabganj", label: "Nawabganj" },
    { value: "rajbari baliakandi", label: "Rajbari Baliakandi" },
    { value: "rajbari pangsha", label: "Rajbari Pangsha" },
    { value: "rajbari town", label: "Rajbari Town" },
    { value: "savar", label: "Savar" },
    { value: "shariatpur naria", label: "Shariatpur Naria" },
    { value: "shariatpur town", label: "Shariatpur Town" },
    { value: "tangail basail", label: "Tangail Basail" },
    { value: "tangail bhuapur", label: "Tangail Bhuapur" },
    { value: "tangail deldur", label: "Tangail Deldur" },
    { value: "tangail ghatail", label: "Tangail Ghatail" },
    { value: "tangail gopalpur", label: "Tangail Gopalpur" },
    { value: "tangail kalihati", label: "Tangail Kalihati" },
    { value: "tangail kashkawlia", label: "Tangail Kashkawlia" },
    { value: "tangail madhupur", label: "Tangail Madhupur" },
    { value: "tangail mirzapur", label: "Tangail Mirzapur" },
    { value: "tangail nagarpur", label: "Tangail Nagarpur" },
    { value: "tangail sakhipur", label: "Tangail Sakhipur" },
    { value: "tangail town", label: "Tangail Town" },
    { value: "tongi", label: "Tongi" },
];


export const Khulna = [
    { value: "bagerhat", label: "Bagerhat" },
    { value: "chuadanga", label: "Chuadanga" },
    { value: "jashore", label: "Jashore" },
    { value: "jhenaidah", label: "Jhenaidah" },
    { value: "khulna aliapur", label: "Khulna Aliapur" },
    { value: "khulna amadee", label: "Khulna Amadee" },
    { value: "khulna batiaghat", label: "Khulna Batiaghat" },
    { value: "khulna chalna bazar", label: "Khulna Chalna Bazar" },
    { value: "khulna digalia", label: "Khulna Digalia" },
    { value: "khulna dumuria", label: "Khulna Dumuria" },
    { value: "khulna paikgachha", label: "Khulna Paikgachha" },
    { value: "khulna terokhada", label: "Khulna Terokhada" },
    { value: "khulna town", label: "Khulna Town" },
    { value: "kushtia", label: "Kushtia" },
    { value: "magura", label: "Magura" },
    { value: "meherpur", label: "Meherpur" },
    { value: "narail", label: "Narail" },
    { value: "satkhira", label: "Satkhira" },
];


export const Mymensingh = [
    { value: "jamalpur dewangonj", label: "Jamalpur Dewangonj" },
    { value: "jamalpur islampur", label: "Jamalpur Islampur" },
    { value: "jamalpur madarganj", label: "Jamalpur Madarganj" },
    { value: "jamalpu malandah", label: "Jamalpur Malandah" },
    { value: "jamalpur shorishbari", label: "Jamalpur Shorishbari" },
    { value: "jamalpur town", label: "Jamalpur Town" },
    { value: "mymensingh gaforgaon", label: "Mymensingh Gaforgaon" },
    { value: "mymensingh gouripur", label: "Mymensingh Gouripur" },
    { value: "mymensingh haluaghat", label: "Mymensingh Haluaghat" },
    { value: "mymensingh isshwargonj", label: "Mymensingh Isshwargonj" },
    { value: "mymensingh muktagacha", label: "Mymensingh Muktagacha" },
    { value: "mymensingh nandail", label: "Mymensingh Nandail" },
    { value: "mymensingh phulpur", label: "Mymensingh Phulpur" },
    { value: "mymensingh town", label: "Mymensingh Town" },
    { value: "mymensingh trishal", label: "Mymensingh Trishal" },
    { value: "netrakona", label: "Netrakona" },
    { value: "sherpur", label: "Sherpur" },
];


export const Rajshahi = [
    { value: "bagura", label: "Bagura" },
    { value: "chapai nawabganj", label: "Chapai Nawabganj" },
    { value: "joypurhat", label: "Joypurhat" },
    { value: "naogaon", label: "Naogaon" },
    { value: "natore", label: "Natore" },
    { value: "pabna", label: "Pabna" },
    { value: "rajshahi", label: "Rajshahi" },
    { value: "sirajganj", label: "Sirajganj" },
];


export const Rangpur = [
    { value: "dinajpur", label: "Dinajpur" },
    { value: "gaibandha", label: "Gaibandha" },
    { value: "kurigram", label: "Kurigram" },
    { value: "lalmonirhat", label: "Lalmonirhat" },
    { value: "nilphamari", label: "Nilphamari" },
    { value: "nilphamari saidpur", label: "Nilphamari Saidpur" },
    { value: "panchagarh", label: "Panchagarh" },
    { value: "rangpur", label: "Rangpur" },
    { value: "thakurgaon", label: "Thakurgaon" },
];


export const Sylhet = [
    { value: "balaganj", label: "Balaganj" },
    { value: "bianibazar", label: "Bianibazar" },
    { value: "bishwanath", label: "Bishwanath" },
    { value: "fenchuganj", label: "Fenchuganj" },
    { value: "goainhat", label: "Goainhat" },
    { value: "golapganj", label: "Golapganj" },
    { value: "habiganj", label: "Habiganj" },
    { value: "jakiganj", label: "Jakiganj" },
    { value: "kanaighat", label: "Kanaighat" },
    { value: "moulvibazar", label: "Moulvibazar" },
    { value: "sunamganj", label: "Sunamganj" },
    { value: "sylhetsadar", label: "SylhetSadar" },
];
